### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by Chofoteddy** [AddExtension/generator-joomla#8]
I think this extension is great idea, but I can't find where is documentation. Please add more information in the README file or create a Wiki :smiley: .

**Comment by digitalgarage** [comment]
Hi @Chofoteddy. This isn't my project but try this.

You'd need Yeoman first so


`npm install -g yo`

Then install the generator

`npm install -g generator-joomla`

Then in your project dir run the generator with 

`yo joomla`

Assumes you have npm installed and working. 

Eric.

**Comment by fede91it** [comment]
Yes, @digitalgarage has said the right procedure.

Actually we doesn't have a documentation and the project is still in development. We are happy if you would contribute to the project.
